### ISSUE TITLE
Files missing on PyPI

### ISSUE THREAD

**Issue by chrysn** [RazerM/ratelimiter#6]
While creating a Debian package for ratelimiter (as described on <https://bugs.debian.org/880661>), I found that the non-empty files in `tests/ ` are missing, and that only one of the two README files (which appear to have diverged) are provided.

Please consider adding the tests via MANIFEST.in (eg. as described [on stackoverflow](https://stackoverflow.com/questions/24727709/do-python-projects-need-a-manifest-in-and-what-should-be-in-it#24727824)), and having one up-to-date README that is shipped the same way.

**Comment by RazerM** [comment]
I will fix the manifest.

The README files have not diverged, pandoc output from markdown to rst is the same. Nevertheless, I will remove the Markdown one and keep the rst format.

**Comment by RazerM** [comment]
1.2.0.post0 released on PyPI
